# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=140)),
                ('place', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('event_date', models.DateTimeField()),
                ('event_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
