# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160313_1943'),
        ('community_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.MyUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 13, 23, 26, 41, 189911, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 13, 23, 26, 52, 452586, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='centraal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=140),
        ),
    ]
