# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_event', '0003_event_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(default='svsv'),
            preserve_default=False,
        ),
    ]
