# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_event', '0004_event_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='user.Skill'),
        ),
    ]
