# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_event', '0005_auto_20160314_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='events', to='user.Skill'),
        ),
    ]
