# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0020_auto_20160331_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MyUser')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
