# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20160315_1455'),
        ('sensei_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='demo_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
