# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensei_stuff', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Batch'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='sensei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensei', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sensei_stuff.Challenge'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
