# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_stuff', '0002_auto_20160315_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='sensei',
        ),
    ]
