# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20160315_1455'),
        ('sensei_stuff', '0003_auto_20160315_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='sensei',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.MyUser'),
            preserve_default=False,
        ),
    ]
