# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_myuser_user_type'),
        ('sensei_stuff', '0007_auto_20160316_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed_user',
            field=models.ManyToManyField(related_name='users', to='user.MyUser'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='sensei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensei', to='user.MyUser'),
        ),
    ]
