# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 23:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_myuser_user_type'),
        ('sensei_stuff', '0009_auto_20160316_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 16, 23, 55, 47, 319656, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.MyUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sensei_stuff.Challenge'),
        ),
    ]
