# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sensei_stuff', '0010_auto_20160316_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='completed_user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 17, 21, 19, 33, 343090, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to='user.MyUser'),
        ),
    ]
