# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160313_1943'),
        ('shared_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.RemoveField(
            model_name='file',
            name='skill',
        ),
        migrations.AddField(
            model_name='file',
            name='skill',
            field=models.ManyToManyField(related_name='shared_files', to='user.Skill'),
        ),
    ]
