# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
