# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_myuser_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.CharField(blank=True, choices=[('android', 'android'), ('python', 'python'), ('ios', 'ios')], max_length=15),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='batch',
            field=models.CharField(blank=True, choices=[('5', 'batch 5'), ('2', 'batch 2'), ('7', 'batch 7'), ('9', 'batch 9'), ('4', 'batch 4'), ('10', 'batch 10'), ('6', 'batch 6'), ('8', 'batch 8'), ('1', 'batch 1'), ('3', 'batch 3')], max_length=10),
        ),
    ]
