# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20160313_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='batch',
            field=models.CharField(blank=True, choices=[('9', 'batch 9'), ('1', 'batch 1'), ('10', 'batch 10'), ('4', 'batch 4'), ('3', 'batch 3'), ('2', 'batch 2'), ('8', 'batch 8'), ('5', 'batch 5'), ('7', 'batch 7'), ('6', 'batch 6')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(related_name='users', to='user.MyUser'),
        ),
    ]
