# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20160313_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batchs',
            },
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='batch',
        ),
        migrations.AddField(
            model_name='myuser',
            name='batch',
            field=models.ManyToManyField(to='user.Batch'),
        ),
    ]
