# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160313_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='myuser',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='user.Skill'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='batch',
            field=models.ManyToManyField(related_name='batches', to='user.Batch'),
        ),
    ]
