# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20160314_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='skill',
            field=models.ManyToManyField(blank=True, to='user.Skill'),
        ),
    ]
