# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20160315_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='my_users', to='user.Skill'),
        ),
    ]
