# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_myuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cinta',
                'verbose_name_plural': 'Cintas',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='cinta',
            field=models.ManyToManyField(related_name='my_users', to='user.Cinta'),
        ),
    ]
