# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20160331_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('alumni', 'alumni'), ('sensei', 'sensei'), ('admin', 'admin')], max_length=50),
        ),
    ]
