# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20160405_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_type',
        ),
    ]
